import type { Metadata } from "next";
import "./globals.css";
import "@/features/novel/styles/prosemirror.css";

import Providers from "@/components/providers";
import { fontHeading, fontSans } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Enterprise Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontHeading.variable} font-sans antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
